name: cattle_weight_estimator
description: A Flutter application for cattle weight estimation.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0' # Updated to a more recent stable SDK version

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.11.0
  image_picker: ^1.0.4
  image: ^4.2.0
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cow_weight_model.tflite